name = "Hyperion Community Server Next"
author = "Clamatus"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d9219a9baf4b556558605da739b53c45520f97cd1a06d0e12a08789887cb809f"

[versions]
forge = "47.2.20"
minecraft = "1.20.1"
