name = "Hyperion Community Server Next"
author = "Clamatus"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4332b1f1cd0db001765d218f0e84398c330e348f104468fed4b220cb2e58db2a"

[versions]
forge = "47.2.20"
minecraft = "1.20.1"
